# mac freezes with batch_size = 1024, but doesn't crash... to investigate
# super slow with 512 batch size
batch_size = 128
input_dimensions = 256

# Sequence related parameters
sequence_length = 128
num_heads = 8

# Learning rate
learning_rate = 0.00003

# Iteration and save parameters
num_iters = 2000
save_interval = 10
eval_interval = 100

