# This is the config file for the simple train
# It uses a tokenizer that's just the vocab of the shakespeare dataset
checkpoint_dir = './checkpoints/maxi'
dataset = 'maxi'
tokenizer = 'bert'

# At the moment they use the same hyperparameters, but this may change
hyperparameters = 'hyperparameters.toml'
